config/routes.rb
Rails.application.routes.draw do
  get 'areas/index'
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :home, only:[:index]
  resources :areas

  # get 'home/index'
  # devise_for :users
  
  # devise_scope :user do
  #   get "/users/sign_out" => "devise/sessions#destroy"
  # end

  # root 'home#index'

  # resources :home, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
      @areas = Area.all
  end

  def new
      @area = Area.new
  end

  def create
      @area = Area.create(
          codigo_area: params[:area][:codigo_area],
          nombre_area: params[:area][:nombre_area])
      if @area.save 
          redirect_to areas_path
      else 
          render :new 
      end
  end

  def edit
      
  end

  def update
      @area =  Area.find(params[:codigo_area])
      Area.update(
          codigo_area: params[:codigo_area],
          nombre_area: params[:nombre_area]
      )
  end


  def show
      @area = Area.find(params[:id])
  end

  def destroy
      @area = Area.find(params[:id])
      @area.destroy
      redirect_to areas_path

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/proyect_controller.rb
class ProyectController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proyect_helper.rb
module ProyectHelper
end

app/views/areas/_area.html.erb
<tr>
    <td><%= area.codigo_area %></td>
    <td><%= area.nombre_area %></td>
    <td> <%= link_to "Ver", area_path(area.id) %></td>
    <td><%= link_to 'Eliminar', area,
        data: { 
            "turbo-method": :delete,
            controller: "confirmation",
            "confirmation-message-value": 'Are you sure?',
            action: "confirmation#confirm"
            } %>
    </td>
</tr>

app/views/areas/index.html.erb
<body>
    <nav class= "nav_index">
      <img src="https://lostramites.com.co/wp-content/uploads/logo-sena-Naranja-300x300.jpg" id="Index_Logo">
        <section id="Index_Salir">
            <div id="Texto_Salir">
                <a id="cerrar_sesion" href="#"><%= link_to "Salir", destroy_user_session_path, :method => :detele%></a>
            </div>
        </section>
    </nav>

    <main class="main_index">
        <section class="Container_Lista">
            <div id="Titulo_Menu">
                <h2 id="h2_index">Titulo</h2>
            </div>
            <div id="Menu_index">
                <ul class="Home_Listas">
                    
                    <li class="Lista1"><a href="#">Nueva Area</a></li>
                    <li class="Lista1"><a href="#">Editar Area</a></li>


                    
                    
                    
                </ul>
            </div>
            <div id= boton_volver> <%= link_to "Volver", home_index_path , method: :get %>
            </div>
            
        </section>

        <section id="Index_Bienvenida">
            <table>
                <tr>
                    <td>codigo</td>
                    <td>nombre</td>
                </tr>
                <%= render @areas %>
            </table>
        </section>
        
    </main>

    <footer>
        <div id="info-footer">Version 1.0.0</div>
    </footer>
</body>

app/views/areas/new.html.erb
<body id= "body_style">
<main class= "main_new">
<section class= "section_new">
<div class="text_new">
<h2>Crear Nueva Area</h2>
</div>
<div class="div_new">
<%= simple_form_for @area do |f| %>
  <%= f.input :codigo_area %>
  <br>
  <%= f.input :nombre_area %>
  <br >
  <%= f.button :submit %>
<% end %>
</div>
</section>
</body>

app/views/areas/show.html.erb
<body id="body_style">
    <nav class= "nav_index">
      <img src="https://lostramites.com.co/wp-content/uploads/logo-sena-Naranja-300x300.jpg" id="Index_Logo">
        <section id="Index_Salir">
            <div id="Texto_Salir">
                <a id="cerrar_sesion" href="#"><%= link_to "Salir", destroy_user_session_path, :method => :detele%></a>
            </div>
        </section>
    </nav>

    <main class="main_index">
        <section class="Container_Lista">
            <div id="Titulo_Menu">
                <h2 id="h2_index">Titulo</h2>
            </div>
            <div id="Menu_index">
                <ul class="Home_Listas">
                    
                    <li class="Lista1Area"><%= link_to "Nueva Area", new_area_path, :method => :get %></li>
                    <li class="Lista1"><a href="#">Editar Area</a></li>


                    
                    
                    
                </ul>
            </div>
            <div id= boton_volver> <%= link_to "Volver", home_index_path , method: :get %>
            </div>
            
        </section>

        <section id="Index_Bienvenida">
            <p>
                <strong>Codigo:</strong>
                <%= @area.codigo_area %>
            </p>
      
            <p>
                <strong>nombre:</strong>
                <%=  @area.nombre_area %>
            </p>
        </section>
        
    </main>

    <footer>
        <div id="info-footer">Version 1.0.0</div>
    </footer>
</body>

app/views/home/index.html.erb
<body id= "body_style">
    <nav class= "nav_index">
      <img src="https://lostramites.com.co/wp-content/uploads/logo-sena-Naranja-300x300.jpg" id="Index_Logo">
        <section id="Index_Salir">
            <div id="Texto_Salir">
                <a id="cerrar_sesion" href="#"><%= link_to "Salir", destroy_user_session_path, :method => :detele%></a>
            </div>
        </section>
    </nav>

    <main class="main_index">
        <section class="Container_Lista">
            <div id="Titulo_Menu">
                <h2 id="h2_index">Titulo</h2>
            </div>
            <div id="Menu_index">
                <ul class="Home_Listas">
                    <li class="Lista1"><%= link_to "Areas", areas_index_path, :method => :get %></li>
                   
                    
                </ul>
            </div>
            
        </section>

        <section id="Index_Bienvenida">
            <h2>Bienvenidos</h2>
        </section>
        
    </main>

    <footer>
        <div id="info-footer">Version 1.0.0</div>
    </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>